// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package frontend

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"github.com/rank1zen/kevin/internal/ddragon"
	"io"
)

// Sprite is a sprite.
type Sprite struct {
	SpriteMap string

	BGHeight int

	BGWidth int

	Height int

	Width int

	X int

	Y int
}

func (m Sprite) build() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		// TODO: dynamically generating these without tailwind might be
		// easier
		spriteMap := fmt.Sprintf("bg-[url(%s)]", m.SpriteMap)
		bgPosition := fmt.Sprintf("bg-position-[-%dpx_-%dpx]", m.X, m.Y)
		bgSize := fmt.Sprintf("bg-size-[%dpx_%dpx]", m.BGWidth, m.BGHeight)
		height := fmt.Sprintf("h-[%dpx]", m.Height)
		width := fmt.Sprintf("w-[%dpx]", m.Width)
		var templ_7745c5c3_Var2 = []any{spriteMap, bgPosition, bgSize, height, width}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/frontend/sprite.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func (m Sprite) Render(ctx context.Context, w io.Writer) error {
	return m.build().Render(ctx, w)
}

type ItemSprite struct {
	ItemID int
}

func (m ItemSprite) Render(ctx context.Context, w io.Writer) error {
	item := ddragon.ItemsMap[m.ItemID]

	x, y := item.X/48, item.Y/48

	sprite := Sprite{
		SpriteMap: "/static/sprite/" + "small_" + item.Sprite,
		BGHeight:  280,
		BGWidth:   280,
		Height:    28,
		Width:     28,
		X:         x * 28,
		Y:         y * 28,
	}

	return sprite.Render(ctx, w)
}

// ChampionSprite is a sprite of a champion icon.
type ChampionSprite struct {
	// TODO: change to new champion id type
	ChampionID int

	// Size is the size of the image. Currently supports [TextSizeLG],
	// [TextSize2XL].
	Size TextSize
}

func (m ChampionSprite) Render(ctx context.Context, w io.Writer) error {
	champion := ddragon.ChampionMap[m.ChampionID]
	x, y := champion.X/48, champion.Y/48
	if m.Size == TextSizeLG {
		// 28 x 28
		bgHeight := 84
		if champion.Sprite == "champion5.png" {
			bgHeight = 56 // the last sprite map is not the usual height. this is bec.
		}

		sprite := Sprite{
			SpriteMap: "/static/sprite/" + champion.Sprite,
			BGHeight:  bgHeight,
			BGWidth:   280,
			Height:    28,
			Width:     28,
			X:         x * 28,
			Y:         y * 28,
		}

		return sprite.Render(ctx, w)
	} else {
		// 36 x 36 i.e. we want 40 x 40 crop out 2 pixels on each side
		size := 40
		bgHeight := size * 3
		bgWidth := size * 10
		if champion.Sprite == "champion5.png" {
			bgHeight = size * 2 // the last sprite map is not the usual height. this is bec.
		}

		sprite := Sprite{
			SpriteMap: "/static/sprite/" + champion.Sprite,
			BGHeight:  bgHeight,
			BGWidth:   bgWidth,
			Height:    36,
			Width:     36,
			X:         x*40 + 2,
			Y:         y*40 + 2,
		}

		return sprite.Render(ctx, w)
	}
}

// SummonerSprite is a sprite of a summoner spell icon.
//
// NOTE: currently only in 18px
type SummonerSprite struct {
	SummonerID int
}

func (m SummonerSprite) Render(ctx context.Context, w io.Writer) error {
	summ := ddragon.SummonerMap[m.SummonerID]
	x, y := summ.X/48, summ.Y/48

	size := 18

	sprite := Sprite{
		SpriteMap: "/static/sprite/" + "tiny_" + summ.Sprite,
		BGHeight:  size * 4,
		BGWidth:   size * 10,
		Height:    size,
		Width:     size,
		X:         size * x,
		Y:         size * y,
	}

	return sprite.Render(ctx, w)
}

var _ = templruntime.GeneratedTemplate
