services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - "./database:/var/lib/postgresql/data/"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${KEVIN_USER}
      POSTGRES_PASSWORD: ${KEVIN_PASSWORD}
      POSTGRES_DB: ${KEVIN_DATABASE}
