[tools]
"aqua:tailwindlabs/tailwindcss" = "latest"
"cargo:rustywind" = "latest"
go = "1.25"
golangci-lint = "latest"

[env]
# Application settings
KEVIN_PORT = { required = true }
KEVIN_ENV = { required = true }

# Application secrets from GCP Secret Manager
GCP_SECRET_KEVIN_DATABASE_URL = { required = true }
GCP_SECRET_KEVIN_RIOT_API_KEY = { required = true }

# GCP settings
GCP_REGION = { required = true }
GCP_PROJECT_ID = { required = true }

# GCP Artifact Registry settings
GCP_GAR_LOCATION = { required = true }
GCP_GAR_REPOSITORY = { required = true }
GCP_GAR_IMAGE = { required = true }
GCP_GAR_TAG = { required = true }

# GCP Cloud SQL settings
GCP_CLOUDSQL_INSTANCE = { required = true }
