version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"
  GOLANGCI_LINT_CMD:
    sh: command -v golangci-lint >/dev/null 2>&1 && echo "golangci-lint" || echo "go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest"

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/kevin" --open-browser=false

  templ-mock:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/kevin-storybook-v2" --open-browser=false

  templ-generate:
    desc: Compile templ files into Go
    cmds:
      - go tool templ generate

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./assets/css/input.css -o ./assets/css/output.css --watch"

  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-clean
    cmds:
      - task --parallel tailwind-watch templ

  dev-mock:
    desc: Start development mock with hot reload
    deps:
      - tailwind-clean
    cmds:
      - task --parallel tailwind-watch templ-mock

  lint:
    desc: Run golangci-lint
    cmds:
      - "{{.GOLANGCI_LINT_CMD}} run ./..."

  test:
    desc: Run Go unit tests
    cmds:
      - go test -short ./...
