version: "3"

vars:
  GOLANGCI_LINT_CMD: golangci-lint
  TAILWIND_CMD: tailwindcss
  RUSTYWIND_CMD: rustywind

tasks:
  lint:
    desc: Lint source code
    cmds:
      - "{{.GOLANGCI_LINT_CMD}} run ./..."

  test:
    desc: Run tests
    cmds:
      - go test -short ./...

  fmt:
    desc: Format source code
    cmds:
      - go fmt ./...

  generate:
    desc: Generate Templ and Tailwind CSS
    cmds:
      - "{{.TAILWIND_CMD}} -i ./assets/css/input.css -o ./assets/css/output.css"
      - "{{.RUSTYWIND_CMD}} --write . --output-css-file ./assets/css/output.css"
      - "go tool templ generate"

  build:
    desc: Build server
    cmds:
      - "go build -o kevin ./cmd/kevin"

  vet:
    desc: Vet source code
    cmds:
      - "go vet ./..."

  ci:
    desc: Run CI tasks
    cmds:
      - task: generate
      - git diff --exit-code
      - task: lint
      - task: test
