version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/kevin-storybook-v2" --open-browser=false

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./internal/frontend/static/input.css -o ./internal/frontend/static/output.css --watch"

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ
