#!/usr/bin/env bash
#MISE description="Build image for Artifact Registry"
#USAGE flag "--gcp-project-id <gcp-project-id>" help="Project ID" env="GCP_PROJECT_ID"
#USAGE flag "--gcp-gar-location <gcp-gar-location>" help="Artifact Registry location" env="GCP_GAR_LOCATION"
#USAGE flag "--gcp-gar-repository <gcp-gar-repository>" help="Artifact Registry repository" env="GCP_GAR_REPOSITORY"
#USAGE flag "--gcp-gar-image <gcp-gar-image>" help="Artifact Registry image name" env="GCP_GAR_IMAGE"
#USAGE flag "--gcp-gar-tag <gcp-gar-tag>" help="Artifact Registry image tag" env="GCP_GAR_TAG" default="latest"

docker build . \
    --tag "${usage_gcp_gar_location?}-docker.pkg.dev/${usage_gcp_project_id?}/${usage_gcp_gar_repository?}/${usage_gcp_gar_image?}:${usage_gcp_gar_tag?}" \
    --platform linux/amd64
