#!/usr/bin/env bash
#MISE description="Generate source code"

set -e

tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css

rustywind --write . --output-css-file ./assets/css/output.css

go tool templ generate
