// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/rank1zen/kevin/internal/riot"

type RequestProvider interface {
	UpdateSummoner(region riot.Region, name, tag string) (path string, json []byte)
}

var _ templ.Component

var _ = templruntime.GeneratedTemplate
