// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "context"

type PageFooterData struct {
}

func PageFooter(ctx context.Context, data PageFooterData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"pt-8 pb-16 bg-gray-50 dark:bg-gray-800\"><div class=\"container mx-auto px-4 text-gray-900 md:flex md:justify-between md:items-start md:space-x-8 dark:text-gray-100\"><div class=\"mb-6 md:mb-0\"><h3 class=\"font-semibold mb-3\">Links</h3><ul class=\"space-y-2 text-sm text-gray-700 dark:text-gray-300\"><li><a href=\"/faq\" class=\"hover:underline\">FAQ</a></li></ul></div><div class=\"mb-6 md:mb-0\"><h3 class=\"font-semibold mb-3\">Terms</h3><ul class=\"space-y-2 text-sm text-gray-700 dark:text-gray-300\"><li><a href=\"/privacy\" class=\"hover:underline\">Privacy Policy</a></li><li><a href=\"/terms\" class=\"hover:underline\">Terms of Service</a></li></ul></div><div class=\"mb-6 md:mb-0\"><h3 class=\"font-semibold mb-3\">Connect</h3><ul class=\"space-y-2 text-sm text-gray-700 dark:text-gray-300\"><li><a href=\"https://github.com/rank1zen/kevin\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"hover:underline\">GitHub</a></li></ul></div></div><div class=\"mt-8 text-center text-gray-900/90 dark:text-gray-100/90\">Copyright (c) 2025 RANK1ZEN</div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
