// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/rank1zen/kevin/internal/riot"
)

type HeaderData struct {
	Region riot.Region
}

func Header(ctx context.Context, data HeaderData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex bg-white h-13 gap-x-2 justify-between items-center px-2 dark:bg-black\"><div class=\"flex gap-x-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ExtraMenu{}.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/\" class=\"size-9 items-center justify-center cursor-pointer rounded-lg transition dark:hover:bg-gray-100/5 dark:active:bg-gray-100/20 hover:bg-gray-900/5 focus-visible:inset-ring-blue-500/50 focus-visible:inset-ring-2 focus-visible:outline-0 active:bg-gray-900/20\"></a></div><div class=\"flex flex-1 min-w-3xs max-w-sm gap-x-2 items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SearchBar{}.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		regions := RegionPicker{
			CurrentRegion: data.Region,
			Regions: []RegionEntry{
				{
					Region: riot.RegionBR1,
					Name:   "Brazil",
				},
				{
					Region: riot.RegionEUN1,
					Name:   "Europe Nordic & East",
				},
				{
					Region: riot.RegionEUW1,
					Name:   "Europe West",
				},
				{
					Region: riot.RegionJP1,
					Name:   "Japan",
				},
				{
					Region: riot.RegionKR,
					Name:   "Korea",
				},
				{
					Region: riot.RegionLA1,
					Name:   "LAS",
				},
				{
					Region: riot.RegionLA2,
					Name:   "LAN",
				},
				{
					Region: riot.RegionME1,
					Name:   "Middle East",
				},
				{
					Region: riot.RegionNA1,
					Name:   "North America",
				},
				{
					Region: riot.RegionOC1,
					Name:   "Oceania",
				},
				{
					Region: riot.RegionRU,
					Name:   "Russia",
				},
				{
					Region: riot.RegionSEA,
					Name:   "Southeast Asia",
				},
				{
					Region: riot.RegionTR1,
					Name:   "Turkiye",
				},
				{
					Region: riot.RegionTW2,
					Name:   "Taiwan",
				},
				{
					Region: riot.RegionVN2,
					Name:   "Vietnam",
				},
			},
		}
		templ_7745c5c3_Err = regions.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
