// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package profile

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/rank1zen/kevin/internal"
	"github.com/rank1zen/kevin/internal/component"
	"github.com/rank1zen/kevin/internal/component/shared"
)

func NewMatchHistoryList(matches []internal.SummonerMatch) component.List {
	c := component.List{Style: component.ListStyleRaised, Items: []component.Component{}}

	for _, m := range matches {
		card := MatchHistoryCard{
			ChampionWidget: shared.NewMatchChampionWidget(m.ChampionID, m.ChampionLevel, m.SummonerIDs),
			KDAWidget:      shared.NewKDAWidget(m.Kills, m.Deaths, m.Assists),
			CSWidget:       shared.NewCSWidget(m.CreepScore, m.CreepScorePerMinute),
			RuneWidget:     shared.NewRuneWidget(m.Runes),
			ItemWidget:     shared.NewItemInventory(m.Items, m.VisionScore),
			RankChange:     shared.NewRankDeltaWidget(nil, nil, m.Win),
		}

		drawer := component.Popover{
			ButtonChildren: card,
			PanelChildren:  nil,
		}

		c.Items = append(c.Items, drawer)
	}

	return c
}

func NewMatchHistoryNoMatches() component.List {
	c := component.List{Style: component.ListStyleRaised, Items: []component.Component{}}

	c.Items = append(c.Items, component.ComponentFunc(jlkjksdfjksfjk))

	return c
}

func jlkjksdfjksfjk(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex justify-center items-center w-full h-15\"><span class=\"font-medium text-gray-900/90 dark:text-gray-100/90 text-sm\">No matches played</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func NewMatchDetail(match internal.Match) component.ModalLayout {
	blueSide, redSide := []component.Component{}, []component.Component{}

	for i, m := range match.Participants {
		row := MatchParticipantCard{
			Name:            "XXXX",
			Tag:             "XXXX",
			ChampionWidget:  shared.NewMatchChampionWidget(m.ChampionID, m.ChampionLevel, m.SummonerIDs),
			KDAWidget:       shared.NewKDAWidget(m.Kills, m.Deaths, m.Assists),
			CSWidget:        shared.NewCSWidget(m.CreepScore, m.CreepScorePerMinute),
			RuneWidget:      shared.NewRuneWidget(m.Runes),
			Items:           shared.NewItemInventory(m.Items, m.VisionScore),
			RankDeltaWidget: shared.NewRankDeltaWidget(nil, nil, false),
		}

		if m.TeamID == 100 {
			blueSide[i%5] = row
		} else {
			redSide[i%5] = row
		}
	}

	content := NewMatchScoreboardView(match)

	layout := component.ModalLayout{
		HeaderChildren: nil,
		Children:       content,
	}

	return layout
}

// TODO: rename to MatchXXXX something else
func NewMatchDetailLoader(path string, data string) component.Loader {
	loader := component.Loader{
		Path:     path,
		Data:     data,
		Children: shared.NewLoadingModal(),
	}

	return loader
}

// NewMatchHistoryLoader creates a loading component for match history.
func NewMatchHistoryLoader(path string, data string) component.Loader {
	list := component.List{
		Style: component.ListStyleRaised,
		Items: []component.Component{},
	}

	loader := component.Loader{
		Path:     path,
		Data:     data,
		Children: list,
	}

	list.Items = append(list.Items, component.ComponentFunc(mhc))

	return loader
}

func mhc(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"px-4 h-15 flex justify-center items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = component.Spinner{}.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// MatchHistoryCard displays a match in a summoner's match history.
type MatchHistoryCard struct {
	ChampionWidget shared.Champion

	KDAWidget shared.KDAWidget

	CSWidget shared.CSWidget

	RuneWidget shared.RuneWidget

	ItemWidget shared.ItemInventory

	RankChange shared.RankDeltaWidget
}

func (m MatchHistoryCard) ToTempl(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"px-4 py-3 gap-y-1 gap-x-2 flex flex-wrap justify-between md:flex-nowrap\"><div class=\"flex gap-x-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.ChampionWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.KDAWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.CSWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"flex gap-x-2 md:order-last\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.RankChange.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div class=\"flex gap-x-2 w-full justify-between md:w-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.RuneWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.ItemWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

type MatchParticipantCard struct {
	Name, Tag string

	ChampionWidget shared.Champion

	KDAWidget shared.KDAWidget

	CSWidget shared.CSWidget

	RuneWidget shared.RuneWidget

	Items shared.ItemInventory

	RankDeltaWidget shared.RankDeltaWidget
}

func NewMatchParticipantCard(name, tag string, p internal.Participant) MatchParticipantCard {
	card := MatchParticipantCard{
		Name:            name,
		Tag:             tag,
		ChampionWidget:  shared.NewMatchChampionWidget(p.ChampionID, p.ChampionLevel, p.SummonerIDs),
		KDAWidget:       shared.NewKDAWidget(p.Kills, p.Deaths, p.Assists),
		CSWidget:        shared.NewCSWidget(p.CreepScore, p.CreepScorePerMinute),
		RuneWidget:      shared.NewRuneWidget(p.Runes),
		Items:           shared.NewItemInventory(p.Items, p.VisionScore),
		RankDeltaWidget: shared.NewRankDeltaWidget(nil, nil, false),
	}

	return card
}

func (m MatchParticipantCard) ToTempl(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"flex h-15 gap-x-4 px-4 justify-between items-center\"><div class=\"flex gap-x-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.ChampionWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"flex-1 min-w-0 h-9\"><div class=\"text-sm text-semibold text-gray-900/90 dark:text-gray-100/90 whitespace-nowrap\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(m.Name + "#" + m.Tag)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/component/profile/match.templ`, Line: 187, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.KDAWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.CSWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><div class=\"flex gap-x-2 md:order-last\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.RankDeltaWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><div class=\"flex gap-x-4 w-full justify-between md:w-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.RuneWidget.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.Items.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

type MatchScoreboardView struct {
	BlueSide, RedSide component.Section
}

func NewMatchScoreboardView(match internal.Match) MatchScoreboardView {
	blue := component.List{Style: component.ListStyleRaised, Items: []component.Component{}}

	for _, p := range match.GetTeamParticipants(100) {
		blue.Items = append(blue.Items, NewMatchParticipantCard("XXX", "XXX", p))
	}

	red := component.List{Style: component.ListStyleRaised, Items: []component.Component{}}

	for _, p := range match.GetTeamParticipants(200) {
		red.Items = append(red.Items, NewMatchParticipantCard("XXX", "XXX", p))
	}

	content := MatchScoreboardView{
		BlueSide: component.Section{
			Heading: "Blue Side",
			Content: blue,
		},
		RedSide: component.Section{
			Heading: "Red Side",
			Content: red,
		},
	}

	return content
}

func (m MatchScoreboardView) ToTempl(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"px-2 py-5\"><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.BlueSide.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div><div class=\"mt-10\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.RedSide.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
