// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package profile

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"github.com/rank1zen/kevin/internal"
	"github.com/rank1zen/kevin/internal/component"
	"github.com/rank1zen/kevin/internal/component/shared"
	"github.com/rank1zen/kevin/internal/riot"
)

// NewPage creates a profile page.
func NewPage(ep EndpointProvider, region riot.Region, summoner internal.Summoner, rank *internal.Rank) component.Page {
	page := component.Page{
		Title:          fmt.Sprintf("%s#%s - Kevin", summoner.Name, summoner.Tagline),
		HeaderChildren: shared.DefaultPageHeader(),
		Children:       NewPageBody(ep, region, summoner, rank),
	}

	return page
}

// PageBody is data for a profile page.
type PageBody struct {
	TitleBar PageTitleBar

	Matches []component.Section
}

func NewPageBody(ep EndpointProvider, region riot.Region, summoner internal.Summoner, rank *internal.Rank) PageBody {
	body := PageBody{
		TitleBar: NewPageTitleBar(ep, region, summoner, rank),
		Matches:  []component.Section{},
	}

	for i := range 7 {
		path, data := ep.GetMatchHistory(region, summoner.PUUID, i)

		body.Matches = append(body.Matches, component.Section{
			Heading: GetDay(i).Format("Monday, Jan 2"),
			Content: NewMatchHistoryLoader(path, string(data)),
		})
	}

	return body
}

func (m PageBody) ToTempl(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"px-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.TitleBar.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex flex-col gap-9 max-w-5xl mx-auto\"><div class=\"flex flex-col flex-1 gap-y-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, c := range m.Matches {
			templ_7745c5c3_Err = c.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

type PageTitleBar struct {
	Name, Tag string

	Rank shared.RankWidget

	Champions, LiveMatch component.Modal
}

func NewPageTitleBar(ep EndpointProvider, region riot.Region, summoner internal.Summoner, rank *internal.Rank) PageTitleBar {
	livePath, liveData := ep.GetLiveMatch(region, summoner.PUUID)
	champPath, champData := ep.GetChampionList(region, summoner.PUUID)

	bar := PageTitleBar{
		Name: summoner.Name,
		Tag:  summoner.Tagline,
		Rank: shared.RankWidget{
			Rank:         rank,
			ShowTierName: true,
		},
		Champions: component.Modal{
			ButtonChildren: component.Button{
				Icon: component.ViewListIcon,
			},
			PanelChildren: component.Loader{
				Path:     champPath,
				Data:     string(champData),
				Children: shared.NewLoadingModal(),
			},
		},
		LiveMatch: component.Modal{
			ButtonChildren: component.Button{
				Icon: component.OpenMenuIcon,
			},
			PanelChildren: component.Loader{
				Path:     livePath,
				Data:     string(liveData),
				Children: shared.NewLoadingModal(),
			},
		},
	}

	return bar
}

func (m PageTitleBar) ToTempl(ctx context.Context) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex h-13 max-w-5xl mx-auto items-center gap-x-2 justify-between\"><div class=\"flex items-center gap-x-2\"><h1 class=\"font-bold text-2xl text-gray-900/90 dark:text-gray-100/90\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%s#%s", m.Name, m.Tag))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/component/profile/page.templ`, Line: 109, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.Rank.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div class=\"flex items-center gap-x-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.Champions.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = m.LiveMatch.ToTempl(ctx).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
