name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

concurrency:
  group: staging-push
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Cloud Run

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    environment: staging

    env:
      KEVIN_PORT: ${{ vars.KEVIN_PORT }}
      KEVIN_ENV: ${{ vars.KEVIN_ENV }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_GAR_LOCATION: ${{ vars.GCP_GAR_LOCATION }}
      GCP_GAR_REPOSITORY: ${{vars.GCP_GAR_REPOSITORY}}
      GCP_GAR_IMAGE: ${{vars.GCP_GAR_IMAGE}}
      GCP_GAR_TAG: ${{github.sha}}
      GCP_CLOUDSQL_INSTANCE: ${{vars.GCP_CLOUDSQL_INSTANCE}}
      GCP_SECRET_KEVIN_DATABASE_URL: ${{vars.GCP_SECRET_KEVIN_DATABASE_URL}}
      GCP_SECRET_KEVIN_RIOT_API_KEY: ${{vars.GCP_SECRET_KEVIN_RIOT_API_KEY}}

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'jdx/mise-action@v4'

      - run: 'mise run lint'

      - run: 'mise run test'

      - uses: 'google-github-actions/auth@v3'
        with:
          project_id: '${{ vars.GCP_PROJECT_ID }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'

      - run: 'gcloud auth configure-docker ${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev'

      - run: 'mise run build'

      - run: 'mise run push'

      - run: 'mise run migrate'

      - run: 'mise run deploy'
