name: Run Static Checks and Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  go-test:
    name: Go Tests

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run Taskfile test
        shell: devenv shell bash -- -e {0}
        run: task test

  static-go-checks:
    name: Static Go Checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Check go.mod is tidy
        shell: devenv shell bash -- -e {0}
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Check *_templ.go files are up-to-date
        shell: devenv shell bash -- -e {0}
        run: |
          go tool templ generate
          git diff --exit-code -- '*.go'

      - name: Run Taskfile lint
        shell: devenv shell bash -- -e {0}
        run: task lint

name: Run Static Checks and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: 2024.12.14 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
          # automatically write this mise.toml file
          mise_toml: |
            [tools]
            shellcheck = "0.9.0"
          # or, if you prefer .tool-versions:
          tool_versions: |
            shellcheck 0.9.0
      - run: shellcheck scripts/*.sh