name: Push Staging Build

on:
  workflow_dispatch:

  push:
    branches:
      - main

concurrency:
  group: staging-push
  cancel-in-progress: false

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_GAR_LOCATION: ${{ vars.GCP_GAR_LOCATION }}
  GCP_GAR_REPOSITORY: ${{ vars.GCP_REPOSITORY }}
  GCP_GAR_IMAGE: ${{ github.repository }}
  GCP_GAR_TAG: ${{ github.sha }}
  GCP_SERVICE: ${{ vars.GCP_SERVICE }}
  GCP_REGION: ${{ vars.GCP_REGION }}

jobs:
  push:
    name: Push to Google Cloud

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - name: Authenticate into Google
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      - name: Authenticate Docker to Artifact Registry
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - uses: jdx/mise-action@v4

      - name: Test source
        run: 'mise run test'

      - name: Build image
        run: 'mise run build'

      - name: Push image to Artifact Registry
        run: 'mise run push'

  deploy:
    name: Deploy to Cloud Run

    needs: push

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - name: Authenticate into Google
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      - uses: jdx/mise-action@v4

      - name: Migrate Cloud SQL database
        run: 'mise run migrate'

      - name: Deploy to Cloud Run
        run: 'mise run deploy'
