name: Test

run-name: Run Go tests

on:
  push:
    branches:
      - main
      - dev

jobs:

  go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Verify go.mod is tidy
        run: |
          go mod tidy -go=1.23
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Run all tests
        run: go test -v ./...
