name: Run Static Checks and Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  static-checks:
    name: Run Static Checks

    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v4

        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Check go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Check *_templ.go files are up-to-date
        run: |
          go tool templ generate
          git diff --exit-code

        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  go-test:
    name: Run Go Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Run all short tests
        run: go test -short ./...
